### ISSUE TITLE
Register an Event Handler Using a Magic Lambda Function

### ISSUE THREAD

**Issue by fxsalazar** [pulumi/pulumi-hugo#3642] opened 2023-11-17 18:10 UTC
File: [themes/default/content/docs/clouds/aws/guides/lambda.md](https://www.pulumi.com/docs/clouds/aws/guides/lambda/)

Section: [Register an Event Handler Using a Magic Lambda Function](https://www.pulumi.com/docs/clouds/aws/guides/lambda/#register-an-event-handler-using-a-magic-lambda-function)

Even though the bucket and the lambda function are created, the Event Notification does not get "magically" created in the Bucket.

**Comment by toriancrane** [comment] 2023-11-17 18:17
Thank you @fxsalazar for submitting this issue! Can you share the code that you have defined in your program? That will help us to reproduce the issue on our end.

**Comment by fxsalazar** [comment] 2023-11-17 19:29
Exactly as the docs states:
```ts
import * as aws from "@pulumi/aws";

const bucket = new aws.s3.Bucket("test");

bucket.onObjectCreated("handler-magic", (e) => {
  console.log(e);
});

export const bucketName = bucket.id;
```

**Comment by cnunciato** [comment] 2024-01-12 23:52
Took a look at this myself, and it does seem to work -- at least insofar as I'm understanding the issue. See below, which shows that after an initial deployment, uploading a file triggers the Lambda through an event subscription and notification: 

![image](https://github.com/pulumi/pulumi-hugo/assets/274700/46471daf-5881-47a5-b938-6183c0b90f5e)

@fxsalazar Was there something else that didn't happen as you expected?

**Comment by fxsalazar** [comment] 2024-01-15 18:06
I revisited 2 of the projects where we use Pulumi and I'm guessing that it was on the one with the version locked to `3.48.0` where I encountered this issue.

**Comment by cnunciato** [comment] 2024-01-16 17:45
@fxsalazar Ah great, ok. Guessing this has since been fixed, then. I'll go ahead and close this issue for now, but do let us know if you run into anything like this again. Thank you!

**Closed by cnunciato** 2024-01-16 17:45 UTC
Labels: area/docs, kind/bug, resolution/fixed
