### ISSUE TITLE
Request changes link disappears on smaller screens

### ISSUE THREAD

**Issue by nimbinatus** [pulumi/pulumi-hugo#1965] opened 2022-09-21 15:01 UTC
### What happened?

In chatting with a user, we realized they could not submit changes or report issues with documentation pages directly from the page because they had a smaller screen.

I've attached a video and a couple screenshots to show the issue.

https://user-images.githubusercontent.com/1538692/191537065-b19032c8-b0dc-4f90-95ff-7e0a7b6276b4.mov

![Screen Shot 2022-09-21 at 9 44 07 AM](https://user-images.githubusercontent.com/1538692/191536864-592cbb94-3372-4355-a818-2be778a55dec.png)

![Screen Shot 2022-09-21 at 9 44 15 AM](https://user-images.githubusercontent.com/1538692/191536905-589d3657-86f4-4bc9-9b3b-1410b64cc299.png)

### Steps to reproduce

Open any docs or registry page in a browser window smaller than the 1526px breakpoint.

### Expected Behavior

The `Edit this Page` and `Request a Change` links appear with the `Was this page helpful?` survey on smaller screens.

### Actual Behavior

The `Edit this Page` and `Request a Change` links disappear on smaller screens.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment] 2022-09-23 04:12
this is by design. we do want to relocate the edit this page and request changes link out of the right side bar to solve this problem. your welcome to leave this issue to track that if you'd like.

**Comment by nimbinatus** [comment] 2022-09-23 14:06
I'd like to leave it open considering I've had people asking about why they couldn't find a way to edit the page or report an issue. They were on a smaller laptop screen, so they didn't have the ability to make the page larger.

**Comment by susanev** [comment] 2022-09-23 14:13
😎 its wrapped up in other issues, but ill close this once its addressed.

**Closed** 2023-06-06 04:35 UTC
Labels: area/docs, kind/enhancement, resolution/fixed, resolution/by-design
