### ISSUE TITLE
This package should be called X.509 or certificate services, not TLS

### ISSUE THREAD

**Issue by sanmai-NL** [pulumi/pulumi-hugo#87] opened 2021-04-20 08:32 UTC
File: [themes/default/content/docs/reference/pkg/tls/_index.md](https://www.pulumi.com/docs/reference/pkg/tls/)

**Comment by stack72** [comment] 2021-04-20 08:35
Hi @sanmai-NL 

Thanks for your thoughts here - so this is actually attributed work back to the provider it was scaffolded from

https://github.com/hashicorp/terraform-provider-tls

We are not really in control of the name because it's a derivative work

I'm sorry for the confusion here :/

Paul

**Comment by sanmai-NL** [comment] 2021-04-20 09:30
It’s a direct entry under Pulumi API reference, and as presented here seems only _loosely_ coupled to Terraform:

![image](https://user-images.githubusercontent.com/3374183/115373007-b9a58e80-a1cb-11eb-8902-6e01423edba0.png)

**Comment by lukehoban** [comment] 2023-03-05 21:42
Closing this out as By Design given the current design of the package and the upstream provider.

**Closed by lukehoban** 2023-03-05 21:42 UTC
Labels: kind/enhancement, resolution/by-design

**Comment by sanmai-NL** [comment] 2023-03-06 06:48
@lukehoban See https://github.com/pulumi/pulumi-hugo/issues/87#issuecomment-823129330
