### ISSUE TITLE
Doc request : Document under Get Started, with DigitalOcean cloud provider

### ISSUE THREAD

**Issue by rahul3v** [pulumi/pulumi-hugo#1291] opened 2021-05-07 07:18 UTC
It's been helpful if you can provide few examples using DigitalOcean cloud provider, with Kubernetes, under Get Started section

**Comment by susanev** [comment] 2022-04-02 01:33
@cnunciato pinging you on this, since i know you were just doing content work with digitalocean so thought you might have thoughts.

**Comment by cnunciato** [comment] 2024-01-12 19:49
Closing this as a duplicate of #1813.

**Closed by cnunciato** 2024-01-12 19:49 UTC
Labels: area/docs, kind/enhancement, resolution/duplicate, docs/examples
