### ISSUE TITLE
add support to link to and expand individual pricing page faqs

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi-hugo#1424] opened 2022-04-27 01:47 UTC
just talked with a user who did not know about the faq where we share specific credit examples
even though the faq link was shared with them

it would be so much easier to support folks and share information if we had the ability to link directly to faq questions, with the answer auto-expanded

**Comment by susanev** [comment] 2022-04-27 01:48
and past susan already opened an issue for this, lol
dup of https://github.com/pulumi/pulumi-hugo/issues/1115

**Comment by cnunciato** [comment] 2024-01-12 15:42
Closing as dupe of #1115.

**Closed by cnunciato** 2024-01-12 15:42 UTC
Labels: kind/enhancement, resolution/duplicate, impact/usability, area/marketing
