### ISSUE TITLE
Support gifs

### ISSUE THREAD

**Issue by meagancojocar** [pulumi/pulumi-hugo#2943] opened 2023-05-27 17:09 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be great to be able to have gifs in blog posts. At present, using CleanShotX to generate the gif, only a 7s gif with the lowest resolution is supported. This is a regression from previously being able to upload gifs. 

### Affected area/feature

Blogs

**Comment by susanev** [comment] 2023-05-28 21:20
A few notes..
- this isnt a regression, you can upload gifs if you insist they will eventually break the build as they did last time since hugo has a limit on the amount of data it can process
- the gif file format is intended for short animations and low-qualify video
- i do not believe the gif file format is best to support your needs of long high-quality video
- i highly recommend mp4, or mov, or various other video formats
- our current flow for videos is to upload to youtube and then use their embed code

if we step back from the request to support gifs, you can describe your need abstracted from the file format, then im sure folks can suggest the best file format for your needs.

**Comment by cnunciato** [comment] 2024-01-12 22:30
Closing as this is technically supported, and we're generally using MP4s as well now.

**Closed by cnunciato** 2024-01-12 22:30 UTC
Labels: area/blog, kind/enhancement, resolution/fixed, area/marketing
