### ISSUE TITLE
Crosswalk for AWS documentation on how to create a listener for your ALB is outdated

### ISSUE THREAD

**Issue by KiranGopalakrishnan** [pulumi/pulumi-hugo#2453] opened 2023-01-31 15:38 UTC
File: [themes/default/content/docs/guides/crosswalk/aws/elb.md](https://www.pulumi.com/docs/guides/crosswalk/aws/elb/)

I’m trying to create a simple LoadBalancer using awsx in a custom vpc , and i following this doc https://www.pulumi.com/docs/guides/crosswalk/aws/elb/#creating-a-load-balancer-in-a-custom-vpc
However the code examples in here seems to be outdated ? as the code snippet in here seems to call `alb.createListener`  which i cannot find in the awsx.lb.ApplicationLoadBalancer instance/type

**Comment by lukehoban** [comment] 2023-01-31 15:42
See also https://github.com/pulumi/pulumi-hugo/issues/2281.

**Comment by lukehoban** [comment] 2023-03-06 00:53
Going to close this one out as a dupe of #2281.

**Closed by lukehoban** 2023-03-06 00:53 UTC
Labels: kind/bug, resolution/duplicate
