### ISSUE TITLE
Markdown linting tests intermittently fail and block commits

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi-hugo#2393] opened 2023-01-12 17:26 UTC
### What happened?

I modified a Pulumi Learn page (found at `themes/default/content/learn/pulumi-fundamentals/configure-and-provision/index.md`) to fix a separate issue (https://github.com/pulumi/devrel-team/issues/485). When I staged the file and attempted to commit, the pre-commit linting tests (as executed by `yarn run lint-staged`) fail on other, unmodified files. The list and number of files that "fail" the tests vary every time I try to commit.

### Steps to reproduce

1. Modify a file.
2. Stage the file and attempt to commit.
3. Intermittently, the pre-commit linting tests will fail on other, unmodified files. (This doesn't always happen, and I have not yet been able to reliably reproduce the issue.)

### Expected Behavior

I expected the pre-commit tests to run only on modified/staged files, and if errors are detected (perhaps because the changes came from a fork without pre-commit testing) then I expected the list of files that are causing the error to be consistent and reproducible.

### Actual Behavior

The pre-commit tests seem to run against and flag unmodified files, and the list of files that produce an error varies/changes on every run (even when the tests are run manually using `yarn run lint-staged`).

### Output of `pulumi about`

N/A

### Additional context

Running `make ensure` to ensure that the latest versions are installed doesn't seem to make any difference. Modifying `scripts/lint/lint-markdown.js` and removing the testing for `relref` instances seems to fix the error.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment] 2023-01-15 19:39
i believe it was intentional that it lints everything, so i removed the bug. but that doesn't mean we cant change it.

**Comment by scottslowe** [comment] 2023-01-15 19:52
@susanev OK, sounds good. I still think this issue needs to stay open though, given the intermittent/unpredictable nature of the tests sometimes passing and sometimes failing.

**Comment by susanev** [comment] 2023-01-15 20:33
of course, i think we should do this! i only don't want it tracked with the bugs, since it was implemented as designed.

**Comment by scottslowe** [comment] 2023-01-20 23:32
I'm re-adding the `kind/bug` label because the linting tests fail intermittently and unexpectedly. Today, for example, manually running `scripts/lint.sh` (which in turn invokes `/scripts/lint/lint-markdown.js`) returned 3 errors, 6 errors, 8 errors, 18 errors, and no errors. Because these scripts intermittently fail and because they are set as pre-commit hooks, this is blocking commits.

**Comment by susanev** [comment] 2023-01-20 23:36
can you share the output your getting? and the branch you are running them on?

**Comment by scottslowe** [comment] 2023-01-20 23:40
Here's the output (note that the output varies in the number of files and which files it flags, but the "error" returned is constant):
```
Markdown Lint Results:
    - 929 files parsed.
    - 6 errors found.

Errors:

/Users/slowe/Work/Code/Repos/pulumi-hugo/themes/default/content/what-is/what-is-infrastructure-as-software.md:
Line File Header: Maximum call stack size exceeded.

/Users/slowe/Work/Code/Repos/pulumi-hugo/themes/default/content/what-is/what-is-yaml.md:
Line File Header: Maximum call stack size exceeded.

/Users/slowe/Work/Code/Repos/pulumi-hugo/themes/default/content/whitepapers/delivering-cloud-native-infrastructure-as-code.md:
Line File Header: Maximum call stack size exceeded.

/Users/slowe/Work/Code/Repos/pulumi-hugo/themes/default/content/whitepapers/enterprise-innovation-through-cloud-engineering.md:
Line File Header: Maximum call stack size exceeded.

/Users/slowe/Work/Code/Repos/pulumi-hugo/themes/default/content/whitepapers/point-of-view.md:
Line File Header: Maximum call stack size exceeded.

/Users/slowe/Work/Code/Repos/pulumi-hugo/themes/default/content/why-pulumi/_index.md:
Line File Header: Maximum call stack size exceeded.
```
I can reproduce this on two different systems (both macOS 13.1, both ARM-based Macs) on different branches of the "pulumi-hugo" repository (I've tested both the "master" branch as well as a feature branch with a change to one file). Both systems are running NodeJS 16.17; I suppose I can try a different version of Node.

**Comment by scottslowe** [comment] 2023-01-20 23:59
If switching to Node 18 is "the" fix, then we should update `make ensure` to check for the correct version of Node so that others don't run into this issue.

**Comment by susanev** [comment] 2023-01-21 00:09
are you running this on master? or a another branch?

**Comment by scottslowe** [comment] 2023-01-21 00:10
This occurs both on master and on a feature branch.

**Comment by susanev** [comment] 2023-01-21 00:12
okay im not getting this error on master, i can try on ur banch as well if you can share the name. ive also never seen these errors before in all my work in this repo. my node version is v18.7.0. let me ask a few more folks if they have ever seen them.

**Comment by susanev** [comment] 2023-03-25 23:03
i think folks are resolved, so closing.

**Closed by susanev** 2023-03-25 23:03 UTC
Labels: kind/engineering, resolution/fixed
