### ISSUE TITLE
volumeattachment example issues

### ISSUE THREAD

**Issue by faridsaad** [pulumi/pulumi-hugo#288] opened 2021-06-03 19:37 UTC
File: [themes/default/content/docs/reference/pkg/digitalocean/volumeattachment.md](https://www.pulumi.com/docs/reference/pkg/digitalocean/volumeattachment/)

The example python code snippet causes pulumi to return:
```
    	* Error creating Volume: POST https://api.digitalocean.com/v2/volumes: 422 (request "7ad05cda-2f92-458e-a3f0-651ebcd95148") failed to create volume: invalid volume name. names must be lowercase and alphanumeric
```

Further, even when adjusting the names to be lower case, the example returns the following and doesn't plug the volume to the instance:
```
     Type                                    Name                    Status         Info
 +   pulumi:pulumi:Stack                     pulumi2-dev             created        
 +   ├─ digitalocean:index:Droplet           foobardroplet           created        
 +   ├─ digitalocean:index:Volume            foobarvolume            created        
     └─ digitalocean:index:VolumeAttachment  foobarvolumeattachment  **failed**     1 error
 
Diagnostics:
  digitalocean:index:VolumeAttachment (foobarvolumeattachment):
    error: digitalocean:index/volumeAttachment:VolumeAttachment resource 'foobarvolumeattachment' has a problem: Attribute must be a whole number, got 248900744. Examine values at 'VolumeAttachment.DropletId'.
```

It's not clear to me why the whole number issue comes up or how to get around it.

**Comment by infin8x** [comment] 2021-06-04 22:56
Thanks for letting us know! This breaks down into two existing issues:

- The problem with the example snippet relates to autonaming and is tracked by https://github.com/pulumi/pulumi-digitalocean/issues/240
- The VolumeAttachment issue relates to DigitalOcean's ID format and is tracked by https://github.com/pulumi/pulumi-digitalocean/issues/218

As a result, I'm going to mark this issue as a duplicate of those

**Closed by infin8x** 2021-06-04 22:56 UTC
Labels: kind/question, resolution/duplicate
