### ISSUE TITLE
Formatting issue in python pkg documentation

### ISSUE THREAD

**Issue by orionstudt** [pulumi/pulumi-hugo#1876] opened 2022-08-29 17:34 UTC
### Problem description

- I saw a product documentation issue on the following URL: https://www.pulumi.com/docs/reference/pkg/python/pulumi/#module-pulumi.automation

Formatting seems to be cutting the middle column in half vertically. Viewed on Firefox @ 1920x1200

Screenshot: 
![image](https://user-images.githubusercontent.com/32800478/187263426-4135fd24-6964-42ff-8aee-6b0f17cf7fd3.png)

**Comment by susanev** [comment] 2022-08-30 01:31
@guineveresaenger these files dont live in hugo, it gets generated as part of the docs build. so the docs repo may be the best place for this for now. but prolly can also close as a dupe of 6148 if not otheres.

other related issues to this...
https://github.com/pulumi/docs/issues/6426
https://github.com/pulumi/docs/issues/6148
https://github.com/pulumi/docs/issues/4615
https://github.com/pulumi/docs/issues/5047
https://github.com/pulumi/docs/issues/3534
https://github.com/pulumi/docs/issues/3351
https://github.com/pulumi/docs/issues/1595

**Comment by orionstudt** [comment] 2022-08-30 01:36
Definitely up to you guys. It seems there are related/duplicate issues.

But yea I put it in pulumi/docs because I found the file that matches that url here: https://github.com/pulumi/docs/blob/master/content/docs/reference/pkg/python/pulumi/_index.md

**Comment by susanev** [comment] 2022-08-30 01:44
@orionstudt oh no worries at all!!

**Closed** 2022-09-01 18:29 UTC
Labels: kind/bug, resolution/duplicate
